services:
  vault:
    build:
      context: ./images/vault
      dockerfile: Containerfile
    privileged: true
    depends_on:
      - consul-server
    ports:
      - "8200:8200"
    volumes:
      - ./compose/etc/nsswitch.conf:/etc/nsswitch.conf:ro
      - ./compose/consul/etc/consul.d/90-runtime.hcl:/etc/consul.d/90-runtime.hcl:ro
      - ./compose/vault/etc/vault.d/90-runtime.hcl:/etc/vault.d/90-runtime.hcl:ro
    networks:
      hashicorp:
        aliases:
          - vault

  consul-server:
    build:
      context: ./images/consul-server
      dockerfile: Containerfile
    privileged: true
    ports:
      - "8500:8500"
    volumes:
      - ./compose/etc/nsswitch.conf:/etc/nsswitch.conf:ro
    networks:
      hashicorp:
        aliases:
          - consul

  nomad-server:
    build:
      context: ./images/nomad-server
      dockerfile: Containerfile
    privileged: true
    depends_on:
      - vault
      - consul-server
    ports:
      - "4646:4646"
    volumes:
      - ./compose/etc/nsswitch.conf:/etc/nsswitch.conf:ro
      - ./compose/consul/etc/consul.d/90-runtime.hcl:/etc/consul.d/90-runtime.hcl:ro
      - ./compose/nomad-server/etc/nomad.d/90-runtime.hcl:/etc/nomad.d/90-runtime.hcl:ro
    networks:
      hashicorp:
        aliases:
          - nomad-server

  nomad-client:
    build:
      context: ./images/nomad-client
      dockerfile: Containerfile
    privileged: true
    depends_on:
      - vault
      - nomad-server
      - consul-server
    volumes:
      - ./compose/etc/nsswitch.conf:/etc/nsswitch.conf:ro
      - ./compose/consul/etc/consul.d/90-runtime.hcl:/etc/consul.d/90-runtime.hcl:ro
      - ./compose/nomad-client/etc/nomad.d/90-runtime.hcl:/etc/nomad.d/90-runtime.hcl:ro
    networks:
      hashicorp:
        aliases:
          - nomad-client

networks:
  hashicorp:
    driver: bridge
