#cloud-config
write_files:
  - path: /etc/nomad.d/90-runtime.hcl
    owner: root:nomad
    permissions: "0640"
    content: |
      server_join {
        retry_join = ["provider=aws tag_key=Name tag_value=nomad-server region=us-east-1"]
      }

  - path: /etc/consul.d/90-runtime.hcl
    owner: root:consul
    permissions: "0640"
    content: |
      retry_join = ["provider=aws tag_key=Name tag_value=consul-server region=us-east-1"]
