# Compose containers use Podman's DNS server from /etc/resolv.conf directly.
passwd:     files sss systemd
shadow:     files
group:      files sss systemd
hosts:      files dns myhostname
services:   files sss
netgroup:   sss
automount:  files sss
aliases:    files
ethers:     files
gshadow:    files
networks:   files dns
protocols:  files
publickey:  files
rpc:        files

