# syntax=docker/dockerfile:1

FROM registry.fedoraproject.org/fedora-minimal:latest AS nomad-download

ARG TARGETARCH=amd64
ARG NOMAD_VERSION=2.0.5
ARG CONSUL_VERSION=2.0.3

RUN microdnf -y install ca-certificates curl unzip && microdnf clean all

RUN set -eux; \
    case "${TARGETARCH}" in \
      amd64) nomad_arch=amd64; nomad_sha256=6425e43967bb0b2b4979b0d06da9b06772848b658dae372f1256d51ddcfe53c3 ;; \
      arm64) nomad_arch=arm64; nomad_sha256=63186442061f3f86ec7d10615a91435779a84ed2bf6111bfcba3c0acf71dabb7 ;; \
      *) echo "Unsupported architecture: ${TARGETARCH}" >&2; exit 1 ;; \
    esac; \
    archive="nomad_${NOMAD_VERSION}_linux_${nomad_arch}.zip"; \
    curl --fail --silent --show-error --location \
      --output "/tmp/${archive}" \
      "https://releases.hashicorp.com/nomad/${NOMAD_VERSION}/${archive}"; \
    printf '%s  %s\n' "${nomad_sha256}" "/tmp/${archive}" | sha256sum -c -; \
    unzip -q "/tmp/${archive}" -d /tmp/nomad; \
    install -D -m 0755 /tmp/nomad/nomad /out/usr/bin/nomad

RUN set -eux; \
    case "${TARGETARCH}" in \
      amd64) consul_arch=amd64; consul_sha256=3020eea3fdfd939eb021ecaca105a1513af52b22e76f2ee97ea85acc6ff2f832 ;; \
      arm64) consul_arch=arm64; consul_sha256=7551d8f07cbfb633d260fe27a9f7144ce08f1cb964e31e15788309dfb6c2fda5 ;; \
      *) echo "Unsupported target architecture: ${TARGETARCH}" >&2; exit 1 ;; \
    esac; \
    consul_archive="consul_${CONSUL_VERSION}_linux_${consul_arch}.zip"; \
    curl --fail --silent --show-error --location \
      --output "/tmp/${consul_archive}" \
      "https://releases.hashicorp.com/consul/${CONSUL_VERSION}/${consul_archive}"; \
    printf '%s  %s\n' "${consul_sha256}" "/tmp/${consul_archive}" | sha256sum -c -; \
    unzip -q "/tmp/${consul_archive}" -d /tmp/consul; \
    install -D -m 0755 /tmp/consul/consul /out/usr/bin/consul

FROM quay.io/fedora/fedora-bootc:latest

ARG NOMAD_VERSION=2.0.5
ARG CONSUL_VERSION=2.0.3

LABEL org.opencontainers.image.title="Fedora bootc Nomad client" \
      org.opencontainers.image.version="${NOMAD_VERSION}" \
      org.opencontainers.image.base.name="quay.io/fedora/fedora-bootc:latest"

RUN dnf -y install cloud-init moby-engine \
    && dnf clean all \
    && rm -rf /run/cloud-init /run/dnf /var/cache/dnf /var/cache/libdnf5 /var/lib/cloud /var/lib/dnf /var/lib/docker \
    && rm -f /var/cache/ldconfig/aux-cache /var/log/dnf5.log

COPY --from=nomad-download /out/usr/bin/nomad /usr/bin/nomad
COPY --from=nomad-download /out/usr/bin/consul /usr/bin/consul
COPY nomad.hcl /etc/nomad.d/nomad.hcl
COPY nomad.service /usr/lib/systemd/system/nomad.service
COPY consul.hcl /etc/consul.d/consul.hcl
COPY consul.service /usr/lib/systemd/system/consul.service
COPY consul.sysusers /usr/lib/sysusers.d/consul.conf

RUN systemd-sysusers /usr/lib/sysusers.d/consul.conf \
    && chmod 0640 /etc/nomad.d/nomad.hcl \
    && chown root:root /etc/nomad.d/nomad.hcl \
    && nomad config validate /etc/nomad.d \
    && chmod 0640 /etc/consul.d/consul.hcl \
    && chown root:consul /etc/consul.d/consul.hcl \
    && consul validate /etc/consul.d \
    && systemctl enable cloud-init-local.service cloud-init-main.service cloud-config.service cloud-final.service \
    && systemctl enable docker.service nomad.service consul.service \
    && bootc container lint --fatal-warnings

EXPOSE 4646 4647 4648 8301/tcp 8301/udp
STOPSIGNAL SIGRTMIN+3
CMD ["/sbin/init"]
